name: ci-and-cd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  issues:
    types:
      - opened
      - reopened
      - closed
      - deleted
      - labeled
      - edited
    labels:
      - published
  workflow_dispatch:

jobs:
  deploy-to-gh-page:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install deps
        run: pnpm i --no-frozen-lockfile

      - name: Run build
        run: pnpm run build
        env:
          DEPLOY_TARGET: gh-pages
          OWNER: ${{ github.actor }}
          REPO: ${{ github.event.repository.name }}

      - name: Run deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          cname: zoffy.me

